Repository 0xSpaceShard/starknet-bridge-relayer, pull requests merged in 2023-04, with the labels that each got.

#8 Fix bugs and refactor the relayer code
  Makefile
  docker-compose-dev.yaml
  example.env
  src/common/config/env.validation.ts
  src/common/logger/logger.module.ts
  src/indexer/__mocks__/request.ts
  src/indexer/indexer.interface.ts
  src/indexer/indexer.module.ts
  src/indexer/indexer.service.spec.ts
  src/indexer/indexer.service.ts
  src/indexer/queries/getWithdrawals.ts
  src/relayer/__mocks__/IndexerService_mock.ts
  src/relayer/__mocks__/Web3Service_mock.ts
  src/relayer/relayer.module.ts
  src/relayer/relayer.service.spec.ts
  src/relayer/relayer.service.ts
  src/relayer/relayer.utils.ts
  src/relayer/utils.ts
  src/storage/mongo/mongo.service.ts
  src/web3/abis/MulticallView.json
  src/web3/abis/StarknetTokenBridge.json
  src/web3/web3.constants.ts
  src/web3/web3.service.spec.ts
  src/web3/web3.service.ts
Labels: bug

#9 Feat/cron module
  docker-compose-dev.yaml
  e2e/docker/Dockerfile_ganache
  package.json
  src/app/app.module.ts
  src/cron/cron.module.ts
  src/cron/cron.service.ts
  yarn.lock
Labels: enhancement

#10 Fix/refactor
  example.env
  src/common/config/env.validation.ts
  src/indexer/entities/withdrawal.ts
  src/indexer/indexer.interface.ts
  src/indexer/indexer.service.spec.ts
  src/indexer/indexer.service.ts
  src/indexer/queries/getLastIndexedBlock.ts
  src/indexer/queries/index.ts
  src/relayer/__mocks__/IndexerService_mock.ts
  src/relayer/__mocks__/MongoService_mock.ts
  src/relayer/__mocks__/Web3Service_mock.ts
  src/relayer/__mocks__/data.ts
  src/relayer/relayer.interface.ts
  src/relayer/relayer.service.spec.ts
  src/relayer/relayer.service.ts
  src/web3/web3.service.ts
Labels: Improve code

#13 feat(relayer): upgraded the multicall contract to v2
  src/relayer/__mocks__/data.ts
  src/relayer/relayer.service.spec.ts
  src/relayer/relayer.service.ts
  src/web3/abis/Multicall.json
  src/web3/abis/MulticallView.json
  src/web3/web3.constants.ts
  src/web3/web3.interface.ts
  src/web3/web3.service.ts
Labels: enhancement, Improve code

#16 build: fix Dockerfile and update dockerignore
  .dockerignore
  Dockerfile
Labels: bug

#18 build: add release workflow
  .github/workflows/release.yml
  .release-it.json
  package.json
  yarn.lock
Labels: CICD

#19 fix: set node version
  .circleci/config.yml
Labels: CICD

#20 Add relayer l2 address to indexer compose file
  docker-compose.yaml
  example.env
Labels: bug

#21 Set gas limit per withdrawal
  e2e/test/relayer.e2e-spec.ts
  src/web3/web3.constants.ts
  src/web3/web3.service.ts
Labels: bug

#23 Refactor/relayer
  docker-compose-dev.yaml
  docker-compose.yaml
  e2e/Makefile
  e2e/docker-compose-e2e.yaml
  e2e/e2e.env
  e2e/test/mongo.e2e-spec.ts
  e2e/test/relayer.e2e-spec.ts
  example.env
  src/common/config/env.validation.ts
  src/relayer/__mocks__/data.ts
  src/relayer/relayer.constants.ts
  src/relayer/relayer.service.spec.ts
  src/relayer/relayer.service.ts
Labels: Improve code
